### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by duceppemo** [USDA-VS/snp_analysis#1]
The script vcftofasta.sh at line 244 call for a file "ALL_WGS.xlsx", but it's not present in the dependencies. Can you please add it up?

"script2" has changed a bit since last time I used it. I'm trying to implement all the new changes in my local installation.

**Comment by duceppemo** [comment]
Same for the gbk files for brucella.

**Comment by stuber** [comment]
gbk files placed in directories at .../snp_analysis/portable_scripts/script_dependents/.  

ALL_WGS.xlsx is an internal file.  I'm unable to share it.  It's simply a file containing metadata making a sample's labeling more meaningful.  The getbrucname() function pulls column 32 from the Excel worksheet, putting it to a text file and cleans out some special characters.  The output is "bruc_tags.txt".  It's a single column, text file.

Example:
B00-0012_00BA2308_TX-XXX_XXCA-EXP1
B00-0092_00BA1_TX-321_CA-00A1
B00-0133_00BS1_OH-167_SW-00A

A VCF file named "B00-0012.SNPsZeroCoverage.vcf" will display "B00-0012_00BA2308_TX-XXX_XXCA-EXP1" in tables and trees.

Scripts at .../snp_analysis/bin are internal.  You'll find additional files missing which will require commenting out or creating your own file input.  The scripts at .../snp_analysis/portable will only need the files provide at .../snp_analysis/portable/script_dependents.

Thanks,
Tod

**Comment by duceppemo** [comment]
Hi Tod,

Thanks for explaining what those missing files were used for. I don't need them. I'll just remove them from the script. My version of the SNP analysis pipeline is an hybrid between both versions. I made the "long version" portable! I will share everything with you once polished.

Marco
