### ISSUE TITLE
Pipeline Inspiration

### ISSUE THREAD

**Issue by noahaus** [USDA-VS/snp_analysis#8]
Hello Tod,

I'm a grad student looking to study how to best genotype Mycobacterium Bovis, and vSNP code provides an excellent way to study this workflow. I was wondering if there were any scientific papers that you read that helped to inform your decision making when creating the vSNP program, because I would like to have a paper to complement my study of the program!

**Comment by stuber** [comment]
Hi Noahaus,

Better late than never, hopefully.  Sorry this reply is so late.  If you still have questions please let me know. We haven't gotten a methods paper out yet (coming soon), but previously described here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4718535/

**Comment by noahaus** [comment]
Thank you!
